version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      prod-net:
        ipv4_address: 192.168.68.5
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - '/data/pihole/etc-pihole:/etc/pihole'
      - '/data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart:
      unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
networks:
  prod-net:
    external:
      name: prod-net